### ISSUE TITLE
[storage] able to modify the path and file name

### ISSUE THREAD

**Issue by XiaoYuxin** [cs2103jan2016-w13-2j/todolist#78]
edit the fileHandler class
when user change the path and file name, check whether the path is valid and then store it.
make sure when user reopen the software next time, the data will be written into the new file in the new path instead of the default path.

**Comment by cs2103t** [comment]
Do you want me to specify the path and filename when new DataBase or do you want to internalize it in your class?

**Comment by XiaoYuxin** [comment]
@cs2103t you just pass me the string can already . i do in the database class

**Comment by XiaoYuxin** [comment]
created a new text file to store the user entered new path and file name.
